config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users, only: %i(index show edit update destroy) do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(index create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action ->{load_user_by_email params.dig(:password_reset, :email)},
                only: :create
  before_action ->{load_user_by_email params[:email]}, only: %i(edit update)
  before_action :valid_user, :check_expiration, only: %i(edit update)
  def new; end

  def create
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = t "forgot_password.email_sent"
      redirect_to root_path
    else
      flash.now[:danger] = t "forgot_password.email_not_found"
      render :new
    end
  end

  def edit; end

  def update
    if params[:user][:password].blank?
      @user.errors.add :password, t("errors.cant_be_empty")
      render :edit
    elsif @user.update user_params
      log_in @user
      flash[:success] = t "forgot_password.success"
      redirect_to @user
    else
      flash[:danger] = t "forgot_password.fail"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit :password, :password_confirmation
  end

  def load_user_by_email email
    @user = User.find_by email: email&.downcase
    return if @user

    flash[:danger] = t "forgot_password.email_not_found"
    redirect_to root_path
  end

  def valid_user
    return if @user.activated? && @user.authenticated?(:reset, params[:id])

    flash[:danger] = t "forgot_password.invalid_user"
    redirect_to root_path
  end

  def check_expiration
    return unless @user.password_reset_expired?

    flash[:danger] = t "forgot_password.expired"
    redirect_to new_password_reset_path
  end
end

app/views/password_resets/edit.html.erb
<% provide :title, t("forgot_password.reset_password") %>
<h1><%= t "forgot_password.reset_password" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: password_reset_path(params[:id]) do |f| %>
      <%= render "shared/error_messages" %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password, User.human_attribute_name("password") %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, User.human_attribute_name("confirmation") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t("forgot_password.update_password"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide :title, t("forgot_password.title") %>
<h1><%= t "forgot_password.title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :password_reset, url: password_resets_path do |f| %>
      <%= f.label :email, User.human_attribute_name("email") %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.submit t("forgot_password.submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>