config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users, only: %i(index show edit update destroy) do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(index create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
                                  foreign_key: :follower_id,
                                  dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
                                   foreign_key: :followed_id,
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  attr_accessor :remember_token, :activation_token, :reset_token

  before_save :downcase_email
  before_create :create_activation_digest

  validates :name,
            presence: true,
            length: {maximum: Settings.digit.length_20}
  validates :email,
            presence: true,
            length: {minimum: Settings.digit.length_10,
                     maximum: Settings.digit.length_255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :password,
            presence: true,
            length: {minimum: Settings.digit.length_6},
            allow_nil: true # tao moi van check o has_secure_password
  has_secure_password

  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost:
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_column :remember_digest, User.digest(remember_token)
  end

  def forget
    update_column :remember_digest, nil
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if !token || !digest

    BCrypt::Password.new(digest).is_password? token
  end

  def activate
    update_columns activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns reset_digest: User.digest(reset_token),
                   reset_sent_at: Time.zone.now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < Settings.digit.time_2.hours.ago
  end

  def feed
    Micropost.by_user_ids following_ids << id
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  private

  def downcase_email
    email.downcase!
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest activation_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: %i(new create show)
  before_action :load_user, except: %i(index new create)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: :destroy

  def index
    @pagy, @users = pagy User.all
  end

  def show
    @pagy_microposts, @microposts = pagy @user.microposts.newest
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t "signup.mail_check"
      redirect_to root_path
    else
      flash[:danger] = t "signup.signup_failed"
      render :new
    end
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t "edit_user.user_updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "users.user_deleted"
    else
      flash[:danger] = t "users.user_delete_failed"
    end
    redirect_to users_path
  end

  def following
    @title = t("following").capitalize
    @pagy, @users = pagy @user.following
    render :show_follow
  end

  def followers
    @title = t("followers").capitalize
    @pagy, @users = pagy @user.followers
    render :show_follow
  end

  private
  def user_params
    # Strong Parameters
    params.require(:user)
          .permit :name, :email, :password, :password_confirmation
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = t "user_not_found"
    redirect_to root_path
  end

  def correct_user
    return if current_user? @user

    flash[:danger] = t "not_correct_user"
    redirect_to root_path
  end

  def admin_user
    return if current_user.admin?

    flash[:danger] = t "action_not_allowed"
    redirect_to root_path
  end
end

app/helpers/user_helper.rb
module UserHelper
  def gravatar_for user, options = {size: Settings.digit.size_80}
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t("follow"), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user? @user %>
  <div id="follow_form">
    <% if current_user.following? @user %>
      <%= render "unfollow" %>
    <% else %>
      <%= render "follow" %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, url: yield(:form_url) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name, User.human_attribute_name("name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, User.human_attribute_name("email") %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, User.human_attribute_name("password") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, User.human_attribute_name("confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user.id),
             html: {method: :delete},
             remote: true do |f| %>
  <%= f.submit t("unfollow"), class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.digit.size_50 %>
  <%= link_to user.name, user %>
  | <%= link_to t("delete"), user, method: :delete, data: {confirm: t("confirm")} %>
</li>

app/views/users/edit.html.erb
<% provide :title, t("edit_user.title") %>
<% provide :form_url, user_path(current_user) %>
<% provide :button_text, t("edit_user.save_changes") %>
<h1><%= t("edit_user.heading") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t("user_edit.change"), "https://gravatar.com/emails", target: "_blank" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t("users.title") %>
<h1><%= t "users.heading" %></h1>

<%== pagy_bootstrap_nav @pagy %>

<ul class="users">
  <%= render @users %>
</ul>

<%== pagy_bootstrap_nav @pagy %>

app/views/users/new.html.erb
<% provide :title, t("signup.title") %>
<% provide :form_url, signup_path %>
<% provide :button_text, t("signup.create_account") %>
<h1><%= t("signup.title") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render "follow_form" if logged_in? %>
    <% if @user.microposts.any? %>
      <h3><%= t "microposts.heading" %> (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%== pagy_bootstrap_nav @pagy_microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide :title, @title %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to t("view_my_profile"), @user %></span>
      <span><b><%= t "microposts.plural" %>>:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: Settings.digit.size_30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%== pagy_bootstrap_nav @pagy %>
    <% end %>
  </div>
</div>